---
driver:
  name: vagrant
  gui: true
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: box-cutter/ubuntu1604-desktop
  - name: ubuntu-14.04
    driver_config:
      box: box-cutter/ubuntu1404-desktop
suites:
  - name: default
    run_list:
      - recipe[universe_ubuntu::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
