---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu/xenial64
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu/trusty64
suites:
  - name: default
    run_list:
      - recipe[universe_ubuntu::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
